title: GNE: A deep learning framework for gene network inference by aggregating biological information
tagline: Kishan K C, Rui Li, Feng Cui, Qi Yu, Anne R. Haake
# When building locally, put an empty string. Otherwise, put "/your-repo-name"
# (the "/" is important)
baseurl: "/GNE"
# arXiv ID (as in "https://arxiv.org/abs/[arXiv id]")
arxiv: "300996"
repo:  "https://github.com/kckishan/GNE"

author:
  name: Kishan KC
  url: "http://kishankc.com.np"

# Leave this as is
markdown: kramdown
